import React from "react";
import { render, fireEvent } from "@testing-library/react";
import "@testing-library/jest-dom/extend-expect";
import JobSpanner from "./JobSpanner";

// unit tests generated by ChatGPT.

test("handles file upload correctly", () => {
  const { getByLabelText, getByText } = render(<JobSpanner />);
  
  // Create a mock file
  const file = new File(["dummy content"], "test-file.txt", { type: "text/plain" });

  // Get the hidden file input
  const fileInput = getByLabelText("File Uploader");

  // Simulate file upload
  fireEvent.change(fileInput, { target: { files: [file] } });

  // Check if the uploaded file name is displayed
  expect(getByText("test-file.txt")).toBeInTheDocument();
});
